// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1MSBo5BQuKE0BWIQuWwC20AZVFG7zUr8',
    appId: '1:493878455294:web:62bef8fb3dbeb4b8c3aeaf',
    messagingSenderId: '493878455294',
    projectId: 'wegojim-da9d2',
    authDomain: 'wegojim-da9d2.firebaseapp.com',
    storageBucket: 'wegojim-da9d2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQLcddk4QkSRYeCrv61J90RvLI1a7AyPM',
    appId: '1:493878455294:android:a94b3a87c6537ac9c3aeaf',
    messagingSenderId: '493878455294',
    projectId: 'wegojim-da9d2',
    storageBucket: 'wegojim-da9d2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBizXvITOzuza51GHUwYzTMDyQ5Z3UWFnI',
    appId: '1:493878455294:ios:569bd484c57ab513c3aeaf',
    messagingSenderId: '493878455294',
    projectId: 'wegojim-da9d2',
    storageBucket: 'wegojim-da9d2.appspot.com',
    iosClientId: '493878455294-gevuglaont435uj6r6p614o7o41k47f2.apps.googleusercontent.com',
    iosBundleId: 'com.example.wegojim',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBizXvITOzuza51GHUwYzTMDyQ5Z3UWFnI',
    appId: '1:493878455294:ios:f87a13763ff188fbc3aeaf',
    messagingSenderId: '493878455294',
    projectId: 'wegojim-da9d2',
    storageBucket: 'wegojim-da9d2.appspot.com',
    iosClientId: '493878455294-ksltfslflvbkpk9l2iiltod5htn5iiqk.apps.googleusercontent.com',
    iosBundleId: 'com.example.wegojim.RunnerTests',
  );
}